on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: lint
        run: npm run lint

   test-js:
    runs-on: ubuntu-latest

    steps:

      - name: clone
        run: git clone https://github.com/ant-design/ant-design-pro.git  --depth=1

      - name: cd
        run: cd ant-design-pro

      - name: fetch
        run: npm run fetch:blocks

      - name: install
        run: npm install

      - name: lint
        run: npm run lint
